// Generated by CoffeeScript 1.3.3

/* RAPHAEL CLASS
*/


(function() {

  this.RaphaelMap = (function() {

    function RaphaelMap(container, width, height) {
      this.container = container;
      this.width = width;
      this.height = height;
      this.map = Raphael(this.container, this.width, this.height);
    }

    RaphaelMap.prototype.scale = function(svgs, ratio) {
      var svg, _i, _len, _results;
      _results = [];
      for (_i = 0, _len = svgs.length; _i < _len; _i++) {
        svg = svgs[_i];
        _results.push(svg.scale(ratio, ratio, 0, 0));
      }
      return _results;
    };

    return RaphaelMap;

  })();

}).call(this);
