// Generated by CoffeeScript 1.3.3

/* NATIONALRAT CLASS
*/


(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  this.SoccerMap = (function(_super) {
    var curve, data, field;

    __extends(SoccerMap, _super);

    curve = tageswoche.curve;

    field = tageswoche.field;

    data = tageswoche.data;

    function SoccerMap(container, width, settings) {
      var height, self;
      this.settings = settings != null ? settings : {};
      self = this;
      field.scale = width / field.originalWidth;
      height = width / field.widthHeightRelation;
      SoccerMap.__super__.constructor.call(this, container, width, height);
      this.scenes = [];
      this.red = "#EE402F";
      this.blue = "#0051A3";
      this.white = "#FFFFFF";
      this.circleRadius = 13;
      this.pathAttributes = {
        "default": {
          fill: this.red,
          stroke: "",
          "stroke-width": 1.0,
          "stroke-linejoin": "round"
        }
      };
      this.setup();
    }

    SoccerMap.prototype.setup = function(container, width) {
      var action, scene, _i, _len, _ref;
      scene = data.nextScene();
      _ref = scene.actions;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        action = _ref[_i];
        action.start = field.calcPosition(action.start);
        if (action.end) {
          action.end = field.calcPosition(action.end);
        }
        this.addScene(action);
      }
      return this.draw();
    };

    SoccerMap.prototype.addScene = function(scene) {
      return this.scenes.push(scene);
    };

    SoccerMap.prototype.draw = function() {
      this.drawPasses();
      return this.drawPositions();
    };

    SoccerMap.prototype.drawPasses = function() {
      var lastPosition, scene, _i, _len, _ref, _results;
      lastPosition = void 0;
      _ref = this.scenes;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        scene = _ref[_i];
        if (scene.end) {
          this.drawSprint(scene.start, scene.end);
        }
        if (lastPosition) {
          this.addPass(lastPosition, scene.start);
        }
        _results.push(lastPosition = scene.end ? scene.end : scene.start);
      }
      return _results;
    };

    SoccerMap.prototype.drawPositions = function() {
      var drawStartLabel, scene, startCircleRadius, _i, _len, _ref, _results;
      _ref = this.scenes;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        scene = _ref[_i];
        startCircleRadius = this.circleRadius;
        drawStartLabel = true;
        if (scene.end) {
          this.map.circle(scene.end.x, scene.end.y, this.circleRadius).attr(this.pathAttributes["default"]);
          this.label(scene.end, scene.number);
          startCircleRadius = startCircleRadius / 2;
          drawStartLabel = false;
        }
        this.map.circle(scene.start.x, scene.start.y, startCircleRadius).attr(this.pathAttributes["default"]);
        if (drawStartLabel) {
          _results.push(this.label(scene.start, scene.number));
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };

    SoccerMap.prototype.drawSprint = function(start, end) {
      var path;
      path = curve.wavy(start, end, "10%");
      return this.map.path(path).attr({
        fill: "",
        stroke: this.red,
        "stroke-width": 2
      });
    };

    SoccerMap.prototype.addPass = function(start, end) {
      var endGap, length, path, startGap, subCurve;
      path = curve.curve(start, end, "10%", 0.6, "right");
      startGap = 0;
      endGap = 16;
      length = Raphael.getTotalLength(path);
      subCurve = Raphael.getSubpath(path, startGap, length - endGap);
      this.drawArrow(path, length - endGap);
      return this.map.path(subCurve).attr({
        fill: "",
        stroke: this.white,
        "stroke-width": 2
      });
    };

    SoccerMap.prototype.drawArrow = function(path, endLength) {
      var arrowSize, arrowhead, base, tip;
      arrowSize = 10;
      if ((endLength - arrowSize) > 30) {
        base = Raphael.getPointAtLength(path, endLength - arrowSize);
        tip = Raphael.getPointAtLength(path, endLength);
        arrowhead = curve.arrow(base, tip, 0.3);
        return this.map.path(arrowhead).attr({
          fill: "",
          stroke: this.white,
          "stroke-width": 2
        });
      }
    };

    SoccerMap.prototype.label = function(position, label) {
      var color, font, x;
      color = "#FFFFFF";
      x = position.x;
      if (+label > 9) {
        x -= 1;
      }
      font = '200 16px "Helvetica Neue", Helvetica, "Arial Unicode MS", Arial, sans-serif';
      return this.map.text(x, position.y, label).attr({
        fill: color,
        stroke: "none",
        "font": font
      });
    };

    return SoccerMap;

  })(RaphaelMap);

}).call(this);
